#115 Updated React Configuration in CONTRIBUTING.md
AmanNegi/FreshNest pull request #117
Opened 2023-10-03 09:25 UTC by cheesequake

Updated CONTRIBUTING.md with the latest means of running the React frontend locally.

2023-10-03 09:54 UTC, AmanNegi commented
Hey there, I was expecting to add different guides for different languages in the `CONTRIBUTING.md` file. So basically, the `CONTRIBUTING.md` file will contain **links** to, the React Setup Guide, NodeJS Setup Guide, Flutter Setup Guide, and other basic Styling, Code of Conduct, etc.

So could you update the Guide mentioned in https://github.com/AmanNegi/FreshNest/tree/main/frontend/react#readme and just link it to the `CONTRIBUTING.md`.

2023-10-03 09:54 UTC, AmanNegi commented on docs/CONTRIBUTING.md
> +3. Open the `frontend` folder in your preferred IDE or code editor.
Note, that we have to navigate to `fronted/react`.

2023-10-03 10:01 UTC, AmanNegi reviewed
Hey there, I have added a few comments to this, but ensure these comments are taken care of in the [React Guide](https://github.com/AmanNegi/FreshNest/tree/main/frontend/react#readme). In this [file](https://github.com/AmanNegi/FreshNest/blob/dev-react/docs/CONTRIBUTING.md), you can simply add a link to the React Guide.

2023-10-03 10:01 UTC, AmanNegi commented on docs/CONTRIBUTING.md
>  1. Install Node.js and `npm` on your development machine by following the instructions on the Node.js website.
We need to mention pre-requisitives beforehand, like we need Node `v18.14.0` and `npm`. To use a local backend server the user might even be required to have `MongoDB` installed. So a section, by the name **pre-requisitives** could mention it at the start of this guide.

2023-10-03 10:01 UTC, AmanNegi commented on docs/CONTRIBUTING.md
> +5. Next we will create a `.env` file, which contains the following key-value pairs:
See [here](https://github.com/AmanNegi/FreshNest/tree/main/frontend/react#readme), how it mentions we can use remote as well as local URL.

2023-10-03 16:19 UTC, AmanNegi requested changes
These are the last minor suggestions. Great work so far 🙂

2023-10-03 16:19 UTC, AmanNegi commented on backend/README.md
> +- Node.js [v18.4.0](https://nodejs.org/dist/v18.4.0/)
- Node.js [v18.14.0](https://nodejs.org/dist/v18.14.0/)

2023-10-03 16:19 UTC, AmanNegi commented on backend/README.md
> +Prerequisites:
I would suggest you make the Prerequisites a subheading an `h2`, we can then have a similar **Steps** heading before the steps start.

Eg:
## Prerequisites:
## Steps

2023-10-03 16:19 UTC, AmanNegi commented on backend/README.md
> +npm start
For local development, I would suggest to run `npm run dev` as we have `nodemon` in our `dev-dependencies`.

2023-10-03 16:19 UTC, AmanNegi commented on frontend/react/README.md
> +Prerequisites:
Similar to the above, having a `Prerequisites` and `Steps` subheading(h2) would be helpful.

2023-10-03 16:19 UTC, AmanNegi commented on frontend/react/README.md
> -3. Install Node.js [v18.4.0](https://nodejs.org/dist/v18.4.0/).<br>
- Node.js [v18.14.0](https://nodejs.org/dist/v18.14.0/)

2023-10-03 17:25 UTC, cheesequake commented
@AmanNegi I have made the changes you had mentioned. Thank you!

2023-10-04 02:52 UTC, AmanNegi approved these changes
LGTM!

2023-10-04 02:52 UTC, merged

2023-10-04 02:53 UTC, AmanNegi commented
Great work @cheesequake! Thanks a lot for contributing, Feel free to come back for more issues. 😃