Added Splash Screen
AmanNegi/FreshNest pull request #149
Opened 2023-10-15 19:27 UTC by R0gue-one

Created a draft for the Splash screen. Added app logo and tagline. 

I don't know the font for the tagline so just have used the default font will update ASAP

Resolving issue: https://github.com/AmanNegi/FreshNest/issues/143

2023-10-16 13:12 UTC, AmanNegi commented
Could you share a demo video real quick?

2023-10-16 16:00 UTC, AmanNegi commented
Everything so far looks amazing! Just could you use the app accent color for text. Also avoid pushing `pubspec.lock` changes.

2023-10-16 17:54 UTC, R0gue-one commented
@AmanNegi Sorry for the delay. I have now changed the text color of tagline. Here the preview:

![Screenshot_20231016_231735](https://github.com/AmanNegi/FreshNest/assets/124084350/e8ccda32-1d02-44e7-8784-5dcb449fb6c8)


If you have any suggestions or anything you want to change please let me know.

2023-10-16 17:57 UTC, R0gue-one commented
Also sorry for pushing the changes in `pubsec.lock` I didn't realise it that time, I will keep that in mind now

2023-10-17 01:47 UTC, AmanNegi requested changes
Here's some changes.

2023-10-17 01:47 UTC, AmanNegi commented on frontend/flutter/lib/splash.dart
> +    Navigator.pushReplacement(context, MaterialPageRoute(builder: (context)=>App().getHomePage()));
Feel free to move the `getHomePage` function in this file. Also move the RolePage widget.

2023-10-17 01:47 UTC, AmanNegi commented on frontend/flutter/lib/splash.dart
> +                //rgba(4,141,66,255)
Remove the commented code.

2023-10-17 01:47 UTC, AmanNegi commented on frontend/flutter/lib/splash.dart
> +                color: Color.fromARGB(255,4,141,66),
We have a colors.dart file, you can use the accent color variable here.

2023-10-17 10:11 UTC, AmanNegi approved these changes

2023-10-17 10:13 UTC, AmanNegi commented
@R0gue-one great work, can you remove the `pubspec-lock` changes from this PR? Or should I do it.

It's as simple as downloading the current `pubspec.lock` from the `main` branch and replace it with yours. Then simply commit this change and push it.

2023-10-17 10:14 UTC, R0gue-one commented
> @R0gue-one great work, can you remove the `pubspec-lock` changes from this PR? Or should I do it.
> 
> It's as simple as downloading the current `pubspec.lock` from the `main` branch and replace it with yours. Then simply commit this change and push it.

Sure I'll do it right away

2023-10-17 10:19 UTC, R0gue-one commented
Done !

2023-10-17 10:22 UTC, AmanNegi commented
Looks great! Thanks a lot for contributing to FreshNest. I will merge your PR right away. :smile_cat: :rocket:

2023-10-17 10:23 UTC, merged

2023-10-17 10:24 UTC, R0gue-one commented
Thank you very much having me @AmanNegi and helping me though it !!

2023-10-17 10:27 UTC, AmanNegi commented
Feel free to come back for more issues. :sparkles:

2023-10-17 10:30 UTC, R0gue-one commented
Sure will !

2023-10-25 14:13 UTC, R0gue-one commented
Hey! @AmanNegi there was one thing that I wanted to mention I had a problem while setting up the project, I think we need to add .json file from google services? I didn't know about this as I just started flutter, should we add this to the Readme file under flutter ?

2023-10-25 14:39 UTC, AmanNegi commented
Yes, @R0gue-one we should add this in Readme. Feel free to create an issue and raise a PR as well.

2023-10-25 14:47 UTC, R0gue-one commented
Sure I'll get on it !