Updated .env for GLogin setup in React Setup Docs
AmanNegi/FreshNest pull request #155
Opened 2023-10-18 18:43 UTC by H-SM

hey @AmanNegi , I finished up updating the doc for GLogin Setup in the React Application. Hope it meet the expectations and gets merged up soon. 

Ps.: don't forget to mark the PR as `hacktoberfest-accepted`. Have a great day.

2023-10-19 13:27 UTC, AmanNegi requested changes
Here's some suggestions.

2023-10-19 13:53 UTC, H-SM commented on frontend/react/README.md
> +VITE_GLOGIN_CLIENT_SECRET="YOUR_CLIENT_SECRET"
On it..

2023-10-20 05:43 UTC, H-SM commented on frontend/react/README.md
> +VITE_GLOGIN_CLIENT_SECRET="YOUR_CLIENT_SECRET"
hey @AmanNegi , I looked into these further today... These are the api config for the `firebase` connection for the application, and not for the `google oauth`... oauth requires only the secret and the client ID to the web client thats it... 
Hope you look into it again... :)

2023-10-20 05:55 UTC, AmanNegi commented on frontend/react/README.md
> +VITE_GLOGIN_CLIENT_SECRET="YOUR_CLIENT_SECRET"
You are right @H-SM, upon researching I found that we are only using one `.env` variable for Google Auth, which is:
```env
VITE_GOOGLE_CLIENT_ID=""
```
So just adding this should be fine.

2023-10-20 09:20 UTC, H-SM commented on frontend/react/README.md
> +VITE_GLOGIN_CLIENT_SECRET="YOUR_CLIENT_SECRET"
on it....

2023-10-20 09:27 UTC, H-SM commented
did the required changes here... hope it gtg now. 👌

Ps. @AmanNegi can I contact you personally by any means? I wish to talk to you regrading a few things, I saw your profile and would love to clear a few doubts of mine... that would be great.. Thanks.

2023-10-21 16:31 UTC, AmanNegi approved these changes

2023-10-21 16:32 UTC, AmanNegi commented
@H-SM LGTM! Feel free to mail me at asterjoules@gmail.com or feel free to DM me on Discord (My Username: asterjoules).

2023-10-21 16:33 UTC, merged