React: On login and signup page the logo present at top right should lead to home page when clicked
AmanNegi/FreshNest pull request #204
Opened 2024-11-29 19:35 UTC by niloferh

Addresses issue #203 

Changes (in Login.jsx and SignUp.jsx):
- Created a click handler function that uses `useNavigate` to redirect to the home page
- Added an `onClick` event to the logo so that the click handler is invoked
- Set the cursor to pointer when hovering over logo to let users know it is clickable 
- Set `zIndex: 1` to bring logo element to the front (otherwise only part of the logo area was clickable)

See videos below for the implemented functionality for login and signup pages:

https://github.com/user-attachments/assets/806bf1aa-7577-4b5a-9a8a-3bc0c42328e4

https://github.com/user-attachments/assets/bb3203b9-7433-40a7-91f6-0d6ef67570d1

2024-12-01 18:22 UTC, AmanNegi commented
@niloferh, LGTM! Are you familiar with TailwindCSS, if possible could you directly apply classes instead of using the style attribute?


> Ps: chatgpt might help you achieve that easily.

2024-12-01 18:24 UTC, AmanNegi requested changes
Hey there could you make the requested changes, feel free to ask if you have any queries.

2024-12-01 18:24 UTC, AmanNegi commented on frontend/react/src/pages/Auth/presentation/Login.jsx
> +          style={{ cursor: "pointer", zIndex: 1 }}
Could you directly incorporate this into the `className` attribute, using TailwindCSS(the project is already using TailwindCSS).

2024-12-01 18:24 UTC, AmanNegi commented on frontend/react/src/pages/Auth/presentation/SignUp.jsx
> +          style={{ cursor: "pointer", zIndex: 1 }}
Similarly here.

2024-12-01 18:24 UTC, AmanNegi commented on frontend/react/src/pages/Auth/presentation/SignUp.jsx
> +          onClick={handleLogoClick}
No need to create a seperate function just for a navigate, feel free to use anonymous function in both login and signup pages.

2024-12-01 19:04 UTC, niloferh commented
Hi @AmanNegi, I've made the changes you requested

2024-12-02 01:46 UTC, AmanNegi commented
LGTM @niloferh! Thanks a lot for your contribution. ✨

> You have been kind patient, and included relevant details in your PR and commits, a true spirit for open souce. Thanks for your valuable time! ✨🤗

2024-12-02 01:46 UTC, AmanNegi approved these changes

2024-12-02 01:46 UTC, merged